# Generated by Django 3.2.20 on 2023-09-26 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0090_alter_documentversion_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_Serializer_Finder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serializer', models.CharField(help_text='clase de serializer.', max_length=255, verbose_name='clase de serializer')),
                ('document_type', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype')),
            ],
            options={
                'verbose_name': 'Serializer Finder',
                'verbose_name_plural': 'Serializer Finder',
            },
        ),
    ]
