# Generated by Django 3.2.20 on 2023-09-26 14:58

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('document_states', '0030_auto_20230505_1724'),
        ('unq', '0002_solicitud_solicitud_aviso_ultimo_examen_solicitud_baja_propuesta_solicitud_baja_temporal_solicitud_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisosUNQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permisos', models.JSONField()),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document_states.workflow', verbose_name='Workflow')),
                ('workflow_state', smart_selects.db_fields.ChainedForeignKey(chained_field='workflow', chained_model_field='workflow', on_delete=django.db.models.deletion.CASCADE, sort=False, to='document_states.workflowstate')),
            ],
        ),
    ]
