# Generated by Django 3.2.20 on 2023-09-26 15:13

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unq', '0003_permisosunq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Accion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(blank=True, help_text='identificador de accion.', max_length=255, null=True, verbose_name='identificador')),
            ],
            options={
                'verbose_name': 'Formulario Accion',
                'verbose_name_plural': 'Formulario Acciones',
            },
        ),
        migrations.CreateModel(
            name='Form_Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, help_text='key elemento.', max_length=255, null=True, verbose_name='key')),
                ('label', models.CharField(blank=True, help_text='label.', max_length=255, null=True, verbose_name='label')),
                ('obligatorio', models.BooleanField(blank=True, help_text='obligatorio.', null=True, verbose_name='obligatorio')),
                ('largo', models.IntegerField(blank=True, help_text='largo.', null=True, verbose_name='largo')),
                ('readonly', models.BooleanField(blank=True, help_text='readonly.', null=True, verbose_name='readonly')),
                ('rows', models.IntegerField(blank=True, help_text='rows.', null=True, verbose_name='rows')),
                ('default', models.CharField(blank=True, help_text='default.', max_length=255, null=True, verbose_name='default')),
                ('placeholder', models.CharField(blank=True, help_text='placeholder.', max_length=255, null=True, verbose_name='placeholder')),
                ('clase_css', models.CharField(blank=True, help_text='clase css.', max_length=255, null=True, verbose_name='clase css')),
                ('validar_select', models.BooleanField(blank=True, help_text='validar select.', null=True, verbose_name='validar select')),
                ('checked_value', models.CharField(blank=True, help_text='checked value.', max_length=255, null=True, verbose_name='checked value')),
                ('unchecked_value', models.CharField(blank=True, help_text='unchecked value.', max_length=255, null=True, verbose_name='unchecked value')),
            ],
            options={
                'verbose_name': 'Formulario Campo',
                'verbose_name_plural': 'Formulario Campos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Form_Elemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, help_text='tipo.', max_length=255, null=True, verbose_name='tipo')),
                ('readonly', models.BooleanField(blank=True, help_text='readonly.', null=True, verbose_name='readonly')),
            ],
            options={
                'verbose_name': 'Formulario Elemento',
                'verbose_name_plural': 'Formulario Elementos',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Form_Filtro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, help_text='tipo.', max_length=255, null=True, verbose_name='tipo')),
                ('valor', models.IntegerField(blank=True, help_text='valor.', null=True, verbose_name='valor')),
            ],
            options={
                'verbose_name': 'Formulario Filtro',
                'verbose_name_plural': 'Formulario Filtros',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Form_Filtro_Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(blank=True, help_text='identificador de accion.', max_length=255, null=True, verbose_name='identificador')),
            ],
            options={
                'verbose_name': 'Formulario Filtro Param',
                'verbose_name_plural': 'Formulario Filtro Params',
            },
        ),
        migrations.CreateModel(
            name='Form_Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud', models.CharField(blank=True, help_text='nombre de la solicitud.', max_length=255, null=True, verbose_name='solicitud')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
            },
        ),
        migrations.CreateModel(
            name='Form_Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='identificador.', max_length=255, verbose_name='identificador')),
                ('ruta', models.CharField(help_text='ruta a la imagen.', max_length=255, verbose_name='ruta')),
                ('label', models.CharField(default='imagen', editable=False, help_text='imagen.', max_length=10, verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'Formulario Imagen',
                'verbose_name_plural': 'Formulario Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Form_Multi_Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(blank=True, help_text='identificador de accion.', max_length=255, null=True, verbose_name='identificador')),
            ],
            options={
                'verbose_name': 'Formulario Multi Option',
                'verbose_name_plural': 'Formulario Multi Options',
            },
        ),
        migrations.CreateModel(
            name='Form_Texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='texto.', max_length=255, verbose_name='texto')),
                ('etiqueta', models.CharField(help_text='etiqueta html.', max_length=255, verbose_name='etiqueta html ')),
                ('label', models.CharField(default='texto', editable=False, help_text='texto.', max_length=10, verbose_name='texto')),
            ],
            options={
                'verbose_name': 'Formulario Texto',
                'verbose_name_plural': 'Formulario Textos',
            },
        ),
        migrations.CreateModel(
            name='Form_Multi_Options_Sorteable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, help_text='clave.', max_length=255, verbose_name='clave')),
                ('valor', models.CharField(help_text='valor.', max_length=255, verbose_name='valor')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('form', adminsortable.fields.SortableForeignKey(blank=True, help_text='multi option', null=True, on_delete=django.db.models.deletion.CASCADE, to='unq.form_multi_option', verbose_name='multi option')),
            ],
            options={
                'verbose_name': 'Multi Option Sorteable',
                'verbose_name_plural': 'Multi Options Sorteable',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Form_Filtro_Params_Sorteable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, help_text='clave.', max_length=255, verbose_name='clave')),
                ('valor', models.CharField(help_text='valor.', max_length=255, verbose_name='valor')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('form', adminsortable.fields.SortableForeignKey(blank=True, help_text='multi option', null=True, on_delete=django.db.models.deletion.CASCADE, to='unq.form_filtro_param', verbose_name='multi option')),
            ],
            options={
                'verbose_name': 'Filtro Params Sorteable',
                'verbose_name_plural': 'Filtro Params Sorteable',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Form_Campo_Sorteable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.BooleanField(help_text='campo archivo.', verbose_name='archivo')),
                ('form_error', models.BooleanField(help_text='errores del form.', verbose_name='form errors')),
                ('form_message', models.BooleanField(help_text='mensajes del form.', verbose_name='form mensajes')),
                ('form_same_line', models.CharField(blank=True, choices=[('primero', 'PRIMERO'), ('medio', 'MEDIO'), ('ultimo', 'ULTIMO')], max_length=255, null=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('action', models.ForeignKey(blank=True, help_text='accion.', null=True, on_delete=django.db.models.deletion.CASCADE, to='unq.form_accion', verbose_name='accion')),
                ('field', models.ForeignKey(blank=True, help_text='campo.', null=True, on_delete=django.db.models.deletion.CASCADE, to='unq.form_campo', verbose_name='campo')),
                ('form', adminsortable.fields.SortableForeignKey(blank=True, help_text='formulario', null=True, on_delete=django.db.models.deletion.CASCADE, to='unq.form_formulario', verbose_name='formulario')),
                ('image', models.ForeignKey(blank=True, help_text='imagen.', null=True, on_delete=django.db.models.deletion.CASCADE, to='unq.form_imagen', verbose_name='imagen')),
                ('text', models.ForeignKey(blank=True, help_text='campo texto.', null=True, on_delete=django.db.models.deletion.CASCADE, to='unq.form_texto', verbose_name='texto')),
            ],
            options={
                'verbose_name': 'Campo Sorteable',
                'verbose_name_plural': 'Campos Sorteable',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='form_campo',
            name='elemento_html',
            field=models.ForeignKey(blank=True, help_text='elemento.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_tipo', to='unq.form_elemento', verbose_name='elemento'),
        ),
        migrations.AddField(
            model_name='form_campo',
            name='filtro',
            field=models.ForeignKey(blank=True, help_text='filtro.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_filtro', to='unq.form_filtro', verbose_name='filtro'),
        ),
        migrations.AddField(
            model_name='form_campo',
            name='filtro_params',
            field=models.ForeignKey(blank=True, help_text='filtro params.', null=True, on_delete=django.db.models.deletion.CASCADE, to='unq.form_filtro_param', verbose_name='filtro params'),
        ),
        migrations.AddField(
            model_name='form_campo',
            name='multiOptions',
            field=models.ForeignKey(blank=True, help_text='multi options.', null=True, on_delete=django.db.models.deletion.CASCADE, to='unq.form_multi_option', verbose_name='multi options'),
        ),
        migrations.CreateModel(
            name='Form_Accion_Sorteable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(choices=[('archivo', 'ARCHIVO'), ('texto', 'TEXTO'), ('imagen', 'IMAGEN'), ('key', 'CAMPO(KEY)'), ('label', 'CAMPO(LABEL)'), ('elemento_html', 'CAMPO(ELEMENTO_HTML)'), ('filtro', 'CAMPO(FILTRO)'), ('obligatorio', 'CAMPO(OBLIGATORIO)'), ('largo', 'CAMPO(LARGO)'), ('multiOptions', 'CAMPO(MULTI OPTION)'), ('readonly', 'CAMPO(READONLY)'), ('rows', 'CAMPO(ROWS)'), ('default', 'CAMPO(DEFAULT)'), ('placeholder', 'CAMPO(PLACEHOLDER)'), ('clase_css', 'CAMPO(CLASE_CSS)'), ('validar_select', 'CAMPO(VALIDAR_SELECT)'), ('checked_value', 'CAMPO(CHECKED_VALUE)'), ('unchecked_value', 'CAMPO(UNCHECKED_VALUE)')], max_length=255)),
                ('accion', models.CharField(help_text='accion.', max_length=255, verbose_name='accion')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('form', adminsortable.fields.SortableForeignKey(blank=True, help_text='accion', null=True, on_delete=django.db.models.deletion.CASCADE, to='unq.form_accion', verbose_name='accion')),
            ],
            options={
                'verbose_name': 'Accion Sorteable',
                'verbose_name_plural': 'Accion Sorteable',
                'ordering': ['order'],
            },
        ),
    ]
