# Generated by Django 3.2.20 on 2023-10-30 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unq', '0004_auto_20230926_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud_Campo_Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo', models.CharField(help_text='nombre de campo.', max_length=255, verbose_name='nombre de campo')),
                ('tipo_campo', models.CharField(help_text='tipo de campo.', max_length=255, verbose_name='tipo de campo')),
            ],
            options={
                'verbose_name': 'Solicitud Campo Tipo',
                'verbose_name_plural': 'Solicitud Campos Tipo',
            },
        ),
        migrations.CreateModel(
            name='Solicitud_Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo', models.CharField(help_text='nombre de campo.', max_length=255, verbose_name='nombre de campo')),
                ('valor_campo', models.CharField(help_text='valor de campo.', max_length=255, verbose_name='valor de campo')),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unq.solicitud')),
            ],
            options={
                'verbose_name': 'Solicitud Campo',
                'verbose_name_plural': 'Solicitud Campos',
            },
        ),
    ]
