# Generated by Django 3.2.20 on 2023-10-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unq', '0005_solicitud_campo_solicitud_campo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='aviso_ultimo_examen',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='baja_propuesta',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='baja_temporal',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='cambio_plan',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='equivalencias',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='grilla',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='licencia_examen',
        ),
    ]
