# Generated by Django 3.2.20 on 2023-11-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unq', '0006_auto_20231030_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud_campo',
            name='campo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
