# Generated by Django 3.2.20 on 2023-11-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unq', '0008_rename_campo_solicitud_campo_campos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_campo',
            name='campos',
        ),
    ]
