# Generated by Django 3.2.20 on 2023-11-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unq', '0009_remove_solicitud_campo_campos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitud_Aviso_Ultimo_Examen',
        ),
        migrations.DeleteModel(
            name='Solicitud_Baja_Propuesta',
        ),
        migrations.DeleteModel(
            name='Solicitud_Baja_Temporal',
        ),
        migrations.DeleteModel(
            name='Solicitud_Cambio_Plan',
        ),
        migrations.DeleteModel(
            name='Solicitud_Equivalencias',
        ),
        migrations.DeleteModel(
            name='Solicitud_Grilla',
        ),
        migrations.DeleteModel(
            name='Solicitud_Licencia_Examen',
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.DeleteModel(
            name='Solicitud_Serializer_Finder',
        ),
    ]
