# Generated by Django 3.2.20 on 2023-09-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_comments', '0007_comment_rol_destino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rol_destino',
            new_name='grupo_destino',
        ),
    ]
