# Generated by Django 3.2.20 on 2023-10-25 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0092_documentfile_grupo_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfile',
            name='grupo_destino',
        ),
    ]
